// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Проверяет работоспособность сервиса",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка работы API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthcheckResponse"
                        }
                    }
                }
            }
        },
        "/currencies/latest/": {
            "get": {
                "description": "Получение списка актуальных валют (курса к доллару)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Получение текущего курса валют",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.Currency"
                            }
                        }
                    }
                }
            }
        },
        "/currencies/pair/": {
            "get": {
                "description": "Получение отношения валюты left к валюте right",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currencies"
                ],
                "summary": "Получение курса валютной пары",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Left currency type",
                        "name": "left",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Right currency type",
                        "name": "right",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CurrencyPair"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HealthcheckResponse": {
            "type": "object",
            "properties": {
                "api_name": {
                    "type": "string"
                },
                "api_version": {
                    "type": "string"
                },
                "app_mode": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dtos.Currency": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "rate": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/dtos.CurrencyType"
                }
            }
        },
        "dtos.CurrencyPair": {
            "type": "object",
            "properties": {
                "left": {
                    "$ref": "#/definitions/dtos.CurrencyType"
                },
                "rate": {
                    "type": "number"
                },
                "right": {
                    "$ref": "#/definitions/dtos.CurrencyType"
                }
            }
        },
        "dtos.CurrencyType": {
            "type": "string",
            "enum": [
                "USD",
                "RUB",
                "EUR",
                "JPY"
            ],
            "x-enum-varnames": [
                "USD",
                "RUB",
                "EUR",
                "JPY"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Go Currency API",
	Description:      "Демо-проект на Go с поддержкой PostgreSQL и MongoDB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
