definitions:
  api.HealthcheckResponse:
    properties:
      api_name:
        type: string
      api_version:
        type: string
      app_mode:
        type: string
      status:
        type: string
    type: object
  dtos.Currency:
    properties:
      date:
        type: string
      id:
        type: integer
      rate:
        type: number
      type:
        $ref: '#/definitions/dtos.CurrencyType'
    type: object
  dtos.CurrencyPair:
    properties:
      left:
        $ref: '#/definitions/dtos.CurrencyType'
      rate:
        type: number
      right:
        $ref: '#/definitions/dtos.CurrencyType'
    type: object
  dtos.CurrencyType:
    enum:
    - USD
    - RUB
    - EUR
    - JPY
    type: string
    x-enum-varnames:
    - USD
    - RUB
    - EUR
    - JPY
info:
  contact: {}
  description: Демо-проект на Go с поддержкой PostgreSQL и MongoDB
  title: Go Currency API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Проверяет работоспособность сервиса
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthcheckResponse'
      summary: Проверка работы API
      tags:
      - health
  /currencies/latest/:
    get:
      consumes:
      - application/json
      description: Получение списка актуальных валют (курса к доллару)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.Currency'
            type: array
      summary: Получение текущего курса валют
      tags:
      - currencies
  /currencies/pair/:
    get:
      consumes:
      - application/json
      description: Получение отношения валюты left к валюте right
      parameters:
      - description: Left currency type
        in: query
        name: left
        required: true
        type: string
      - description: Right currency type
        in: query
        name: right
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.CurrencyPair'
      summary: Получение курса валютной пары
      tags:
      - currencies
swagger: "2.0"
